export type DailyMissionPlan = {
  id: string;
  phase: "Fondations" | "Windows" | "Réseau" | "Support sûr" | "Synthèse";
  title: string;
  duration: string;
  objective: string;
  concepts: string[];
  briefing: string[];
  tasks: string[];
  evidence: string;
  challenge: string;
  caution?: string;
  commands?: { command: string; purpose: string }[];
  memoId?: string;
  relatedMissionId?: string;
};

export const PROGRAM_START = "2026-07-25";
export const PROGRAM_END = "2026-08-23";

export const DAILY_PROGRAM: DailyMissionPlan[] = [
  {
    id: "jour-01-point-de-depart",
    phase: "Fondations",
    title: "Établir ton point de départ",
    duration: "20–25 min",
    objective: "Observer un poste Windows sans rien modifier et produire sa première fiche d’identité technique.",
    concepts: ["cpu", "ram", "ssd", "ip", "driver"],
    briefing: [
      "Un technicien commence par établir des faits : matériel, version de Windows, réseau et périphériques visibles.",
      "Une information relevée vaut mieux qu’une impression. « Le PC est lent » n’est pas encore une mesure.",
    ],
    tasks: [
      "Ouvre les Informations système et relève le processeur, la quantité de RAM et la version de Windows.",
      "Dans le Gestionnaire des tâches, repère CPU, mémoire, disque et réseau.",
      "Ouvre le Gestionnaire de périphériques et vérifie seulement si un avertissement est visible.",
      "Relève l’adresse IPv4 active avec ipconfig, sans publier cette information en ligne.",
    ],
    commands: [
      { command: "winver", purpose: "Afficher l’édition et la version de Windows." },
      { command: "msinfo32", purpose: "Ouvrir les Informations système." },
      { command: "ipconfig", purpose: "Afficher la configuration IP synthétique." },
    ],
    evidence: "Écris cinq lignes : Windows, CPU, RAM, stockage principal et adresse IPv4.",
    challenge: "Explique en une phrase pourquoi la RAM et le SSD ne répondent pas au même besoin.",
    caution: "Ne change aucun pilote ni réglage : l’objectif est de construire un état initial fiable.",
    memoId: "method",
  },
  {
    id: "jour-02-chaine-materielle",
    phase: "Fondations",
    title: "Dessiner la chaîne matérielle",
    duration: "20–25 min",
    objective: "Relier chaque composant à sa fonction et comprendre les dépendances entre les maillons.",
    concepts: ["cpu", "ram", "ssd", "psu", "gpu"],
    briefing: [
      "Le CPU exécute, la RAM garde le travail immédiat, le SSD conserve, le GPU produit l’image et le bloc d’alimentation fournit l’énergie.",
      "Un symptôme d’affichage ne condamne donc pas automatiquement le GPU.",
    ],
    tasks: [
      "Dessine cinq cases nommées CPU, RAM, SSD, GPU et bloc d’alimentation.",
      "Sous chaque case, note ce qu’elle reçoit, ce qu’elle produit et ce qui disparaît si elle ne fonctionne plus.",
      "Ajoute deux symptômes possibles par composant, sans écrire de conclusion définitive.",
      "Compare ton schéma aux fiches du glossaire et corrige les confusions.",
    ],
    evidence: "Conserve le schéma : il servira de carte mentale pendant les cas de panne.",
    challenge: "Trouve deux causes différentes pouvant toutes deux produire un écran noir.",
    memoId: "method",
  },
  {
    id: "jour-03-lire-une-lenteur",
    phase: "Fondations",
    title: "Transformer « ça rame » en mesures",
    duration: "20–30 min",
    objective: "Observer l’effet d’une activité réelle sur le CPU, la RAM et le stockage.",
    concepts: ["task-manager", "cpu", "ram", "ssd"],
    briefing: [
      "Une lenteur devient exploitable quand on sait quand elle apparaît et quelle ressource varie.",
      "Une ressource très sollicitée n’est pas forcément défectueuse : il faut identifier le processus et le contexte.",
    ],
    tasks: [
      "Ouvre le Gestionnaire des tâches et observe une minute au repos.",
      "Lance plusieurs onglets ou une application un peu lourde, puis compare CPU, mémoire et disque.",
      "Trie les processus par la ressource qui a le plus changé.",
      "Ferme l’application et vérifie si les valeurs reviennent vers leur état initial.",
    ],
    evidence: "Note la ressource la plus variable, le processus associé et ce que l’expérience prouve réellement.",
    challenge: "Explique pourquoi « 100 % de disque » est un indice, mais pas encore un diagnostic.",
    caution: "N’arrête pas un processus système que tu ne reconnais pas. Observer suffit.",
    memoId: "slow-windows",
  },
  {
    id: "jour-04-intervenir-sans-improviser",
    phase: "Fondations",
    title: "Intervenir sans improviser",
    duration: "15–20 min",
    objective: "Construire une checklist de sécurité avant toute modification logicielle ou matérielle.",
    concepts: ["backup", "least-privilege", "psu"],
    briefing: [
      "Une réparation réussie qui détruit les données reste un échec assez difficile à vendre.",
      "Avant de toucher : autorisation, sauvegarde, état initial, action réversible et moyen de retour.",
    ],
    tasks: [
      "Lis la fiche « Avant toute intervention ».",
      "Écris une checklist de six points utilisable avant une désinstallation, un pilote ou l’ouverture d’un PC.",
      "Classe chaque point : données, sécurité électrique, réversibilité ou communication.",
      "Imagine ce qui se passe si chacun est ignoré.",
    ],
    evidence: "Garde ta checklist dans les notes ; elle sera réutilisée lors des simulations finales.",
    challenge: "Décris un cas où ne rien modifier immédiatement est la décision la plus professionnelle.",
    caution: "Ne jamais ouvrir un bloc d’alimentation, même débranché.",
    memoId: "before-intervention",
  },
  {
    id: "jour-05-trajet-image",
    phase: "Fondations",
    title: "Suivre le trajet de l’image",
    duration: "20–25 min",
    objective: "Diagnostiquer source → sortie → câble → entrée → écran sans ouvrir le PC.",
    concepts: ["gpu", "video-cable"],
    briefing: [
      "Un écran noir peut venir de l’écran, de sa source, du câble, de la sortie ou du GPU.",
      "Le premier test doit être simple, réversible et capable d’éliminer plusieurs hypothèses.",
    ],
    tasks: [
      "Suis physiquement le câble vidéo depuis l’écran jusqu’au PC.",
      "Identifie le câble et l’entrée sélectionnée dans le menu de l’écran.",
      "Repère les sorties de la carte mère et celles d’une éventuelle carte graphique.",
      "Écris l’ordre des quatre premiers contrôles devant un écran sans signal.",
    ],
    evidence: "Conserve une chaîne de contrôle allant du plus externe au plus invasif.",
    challenge: "Pourquoi changer simultanément de câble, d’écran et de port donne-t-il un mauvais test ?",
    memoId: "no-display",
  },
  {
    id: "jour-06-avant-windows",
    phase: "Fondations",
    title: "Comprendre ce qui se passe avant Windows",
    duration: "20–25 min",
    objective: "Reconstituer alimentation → BIOS/UEFI → POST → stockage → Windows.",
    concepts: ["psu", "bios", "cpu", "ram", "ssd"],
    briefing: [
      "Windows n’est pas la première chose qui travaille au démarrage.",
      "Le BIOS/UEFI initialise le matériel, réalise le POST et choisit une entrée de démarrage.",
    ],
    tasks: [
      "Écris les cinq grandes étapes du démarrage dans l’ordre.",
      "Pour chaque étape, imagine un signe observable : voyant, bip, logo ou message.",
      "Distingue : aucun signe de vie, alimentation sans POST, POST réussi mais Windows absent.",
      "Consulte la fiche BIOS/UEFI et corrige ton ordre.",
    ],
    evidence: "Résume ce que prouve, et ne prouve pas, l’apparition du logo du constructeur.",
    challenge: "Pourquoi réinstaller Windows ne peut-il pas réparer un PC qui n’atteint pas le POST ?",
    memoId: "no-display",
  },
  {
    id: "jour-07-cas-ecran-noir",
    phase: "Fondations",
    title: "Cas de synthèse : l’écran noir",
    duration: "25–30 min",
    objective: "Classer des tests d’affichage par information, risque et coût.",
    concepts: ["video-cable", "gpu", "ram", "bios", "psu"],
    briefing: [
      "Cette mission rassemble la chaîne vidéo, le démarrage et les précautions matérielles.",
      "Une hypothèse doit survivre à un test avant de devenir une conclusion.",
    ],
    tasks: [
      "Joue la mission interactive « Le PC s’allume, mais aucun affichage ».",
      "Après chaque réponse, reformule ce que le test permet d’éliminer.",
      "Relis uniquement les fiches sur lesquelles tu as hésité.",
      "Écris ton propre ordre d’intervention en huit étapes maximum.",
    ],
    evidence: "Note le premier moment où tu accepterais d’ouvrir le boîtier.",
    challenge: "Ajoute une branche pour le cas où l’image disparaît seulement au chargement de Windows.",
    memoId: "no-display",
    relatedMissionId: "no-display",
  },
  {
    id: "jour-08-inventaire-windows",
    phase: "Windows",
    title: "Faire l’inventaire d’un poste Windows",
    duration: "20–25 min",
    objective: "Réunir les informations utiles avant une intervention sur Windows.",
    concepts: ["driver", "task-manager", "cpu", "ram", "ssd"],
    briefing: [
      "Version de Windows, matériel détecté et état des pilotes conditionnent la procédure.",
      "Un inventaire utile reste court et lié au symptôme.",
    ],
    tasks: [
      "Relève l’édition et la version avec winver.",
      "Dans les Informations système, note modèle, CPU et RAM.",
      "Dans le Gestionnaire de périphériques, repère affichage, réseau et stockage.",
      "Écris les trois informations que tu demanderais à distance avant d’aider.",
    ],
    commands: [
      { command: "winver", purpose: "Identifier précisément la version de Windows." },
      { command: "msinfo32", purpose: "Centraliser l’inventaire matériel et système." },
      { command: "devmgmt.msc", purpose: "Ouvrir le Gestionnaire de périphériques." },
    ],
    evidence: "Rédige une fiche d’identité de dix lignes maximum.",
    challenge: "Pourquoi « Windows 11 » seul ne suffit-il pas toujours comme information de version ?",
    memoId: "method",
  },
  {
    id: "jour-09-pilote-ou-materiel",
    phase: "Windows",
    title: "Pilote ou matériel ?",
    duration: "20–25 min",
    objective: "Distinguer périphérique absent, désactivé, mal piloté ou physiquement défaillant.",
    concepts: ["driver", "safe-mode", "bios"],
    briefing: [
      "Le pilote traduit les demandes de Windows pour le matériel.",
      "Un avertissement signale un problème, pas automatiquement une panne physique.",
    ],
    tasks: [
      "Liste quatre états possibles d’un périphérique qui ne fonctionne pas.",
      "Pour chacun, écris l’indice à chercher dans Windows ou le BIOS/UEFI.",
      "Classe : vérifier, redémarrer, revenir au pilote précédent, réinstaller, remplacer.",
      "Écris ce qu’un test en mode sans échec apporterait.",
    ],
    evidence: "Produis un tableau « hypothèse / indice attendu / test suivant ».",
    challenge: "Formule deux hypothèses pour un périphérique visible dans le BIOS/UEFI mais absent de Windows.",
    caution: "Ne mets pas à jour un pilote fonctionnel uniquement parce qu’une version plus récente existe.",
  },
  {
    id: "jour-10-demarrage-lent",
    phase: "Windows",
    title: "Mesurer un démarrage lent",
    duration: "20–30 min",
    objective: "Identifier une application de démarrage coûteuse sans désactiver au hasard.",
    concepts: ["task-manager", "ssd", "cpu", "ram"],
    briefing: [
      "Un démarrage lent peut venir du stockage, d’un service ou d’une application.",
      "Une action utile est ciblée, réversible et suivie d’une nouvelle mesure.",
    ],
    tasks: [
      "Chronomètre le temps entre l’ouverture de session et un bureau utilisable.",
      "Observe les applications de démarrage et leur impact indiqué.",
      "Choisis une application non essentielle comme hypothèse, sans la désactiver.",
      "Écris un protocole avant/après en ne changeant qu’un élément.",
    ],
    evidence: "Note la mesure initiale, l’hypothèse et le critère de validation.",
    challenge: "Pourquoi désactiver dix applications d’un coup peut-il améliorer le PC mais produire un mauvais diagnostic ?",
    caution: "Ne désactive rien dont tu ignores le rôle, notamment les outils de sécurité.",
    memoId: "slow-windows",
  },
  {
    id: "jour-11-mode-sans-echec",
    phase: "Windows",
    title: "Isoler avec le mode sans échec",
    duration: "20–25 min",
    objective: "Comprendre ce qu’une comparaison avec le mode sans échec permet de conclure.",
    concepts: ["safe-mode", "driver", "task-manager"],
    briefing: [
      "Le mode sans échec charge moins de pilotes et de services.",
      "Si le symptôme disparaît, il oriente vers un élément non chargé sans encore nommer le coupable.",
    ],
    tasks: [
      "Note ce qui change par rapport à un démarrage normal.",
      "Imagine trois symptômes pour lesquels la comparaison serait informative.",
      "Écris pour chacun ce que signifie « disparaît » puis « persiste ».",
      "Prépare une procédure de retour au démarrage normal.",
    ],
    evidence: "Résume sous la forme : « Si…, alors l’hypothèse… devient plus/moins probable. »",
    challenge: "Pourquoi un problème absent en mode sans échec n’est-il pas forcément causé par un pilote ?",
    caution: "Cette mission ne demande pas de modifier la configuration de démarrage.",
    memoId: "slow-windows",
  },
  {
    id: "jour-12-sauvegarder-avant",
    phase: "Windows",
    title: "Sauvegarder avant de corriger",
    duration: "20–25 min",
    objective: "Distinguer copie, sauvegarde et restauration vérifiable.",
    concepts: ["backup", "ssd", "least-privilege"],
    briefing: [
      "Une sauvegarde existe vraiment si l’on sait où elle se trouve et comment la restaurer.",
      "Un second dossier du même SSD ne protège pas contre la panne du support.",
    ],
    tasks: [
      "Choisis trois catégories de données irremplaçables.",
      "Indique leur emplacement principal et une copie sur un autre support.",
      "Décris un test de restauration non destructif.",
      "Écris ce que tu vérifierais avant de réinstaller Windows pour quelqu’un.",
    ],
    evidence: "Produis une mini-carte « donnée / original / copie / dernier test ».",
    challenge: "Explique la différence entre synchroniser une erreur et disposer d’une version antérieure.",
    memoId: "before-intervention",
  },
  {
    id: "jour-13-application-envahissante",
    phase: "Windows",
    title: "Traiter une application envahissante",
    duration: "20–25 min",
    objective: "Passer d’un processus gourmand à une correction réversible et vérifiable.",
    concepts: ["task-manager", "least-privilege", "safe-mode"],
    briefing: [
      "Un processus gourmand peut être légitime, bloqué, inutile au démarrage ou indésirable.",
      "Arrêter, désactiver au démarrage et désinstaller sont trois actions différentes.",
    ],
    tasks: [
      "Choisis dans le Gestionnaire des tâches un processus d’application connu.",
      "Observe sa consommation et ouvre son emplacement sans modifier les fichiers.",
      "Classe : attendre, fermer, arrêter, désactiver au démarrage, désinstaller.",
      "Note le risque et la manière de vérifier chaque action.",
    ],
    evidence: "Quelle action choisirais-tu si l’application se relançait à chaque démarrage, et pourquoi ?",
    challenge: "Pourquoi le nom inquiétant ou rassurant d’un processus ne suffit-il pas ?",
    caution: "Ne supprime jamais directement un fichier pour « désinstaller » une application.",
    memoId: "slow-windows",
  },
  {
    id: "jour-14-cas-windows-lent",
    phase: "Windows",
    title: "Cas de synthèse : Windows est lent",
    duration: "25–30 min",
    objective: "Séparer mesure, hypothèse, test et correction dans un diagnostic complet.",
    concepts: ["task-manager", "cpu", "ram", "ssd", "safe-mode"],
    briefing: [
      "La plainte « le PC est lent » recouvre plusieurs problèmes.",
      "Le résultat d’un test doit décider de la prochaine branche.",
    ],
    tasks: [
      "Joue la mission interactive « Le poste est devenu très lent ».",
      "À chaque étape, note l’hypothèse principale et une concurrente.",
      "Relis les fiches liées aux hésitations.",
      "Rédige : symptôme, mesure, test, résultat, action, vérification.",
    ],
    evidence: "Le compte rendu doit permettre à quelqu’un d’autre de reprendre l’enquête.",
    challenge: "Ajoute une branche si aucune ressource n’est saturée dans le Gestionnaire des tâches.",
    memoId: "slow-windows",
    relatedMissionId: "slow-windows",
  },
  {
    id: "jour-15-lire-ip",
    phase: "Réseau",
    title: "Lire une adresse IP",
    duration: "20–25 min",
    objective: "Identifier l’adresse du poste, sa passerelle et une adresse 169.254.x.x.",
    concepts: ["ip", "dhcp", "gateway"],
    briefing: [
      "L’adresse IP identifie une interface ; la passerelle sert de sortie vers d’autres réseaux.",
      "Une adresse 169.254.x.x indique souvent que le DHCP n’a pas fourni de configuration.",
    ],
    tasks: [
      "Exécute ipconfig /all et repère l’interface réellement utilisée.",
      "Relève adresse IPv4, passerelle et état du DHCP.",
      "Distingue interfaces actives, déconnectées et virtuelles.",
      "Dessine le trajet poste → passerelle → Internet.",
    ],
    commands: [{ command: "ipconfig /all", purpose: "Afficher les paramètres détaillés des interfaces." }],
    evidence: "Écris : mon interface active est…, son adresse est…, sa passerelle est…",
    challenge: "Pourquoi deux interfaces du même PC peuvent-elles avoir deux adresses IP ?",
    caution: "Ne publie pas la sortie complète de la commande.",
    memoId: "network-windows",
  },
  {
    id: "jour-16-dhcp",
    phase: "Réseau",
    title: "DHCP : obtenir sa configuration",
    duration: "20–25 min",
    objective: "Comprendre DORA et reconnaître un échec d’attribution automatique.",
    concepts: ["dhcp", "ip", "gateway", "dns"],
    briefing: [
      "DHCP signifie Dynamic Host Configuration Protocol.",
      "Discover, Offer, Request, Acknowledge décrivent la demande et l’attribution d’un bail.",
    ],
    tasks: [
      "Lis la fiche DHCP et réécris DORA sans regarder.",
      "Pour chaque étape, précise qui parle : client ou serveur.",
      "Liste les paramètres reçus avec le bail.",
      "Imagine ce que le poste peut faire avec une adresse 169.254.x.x.",
    ],
    evidence: "Dessine quatre flèches client ↔ serveur et annote-les avec DORA.",
    challenge: "Pourquoi un DNS fonctionnel ne suffit-il pas si le poste n’a pas reçu de passerelle ?",
    memoId: "network-windows",
  },
  {
    id: "jour-17-passerelle",
    phase: "Réseau",
    title: "La passerelle, porte de sortie",
    duration: "20–25 min",
    objective: "Distinguer communication locale et accès à un autre réseau.",
    concepts: ["gateway", "ip", "ping"],
    briefing: [
      "Un poste peut communiquer localement sans atteindre Internet.",
      "Tester la passerelle vérifie une partie du chemin local, pas tout l’accès extérieur.",
    ],
    tasks: [
      "Repère la passerelle avec ipconfig.",
      "Teste-la avec ping et note le résultat exact.",
      "Imagine trois raisons pour lesquelles elle répondrait alors qu’un site reste inaccessible.",
      "Imagine deux raisons pour lesquelles elle ne répondrait pas sans être éteinte.",
    ],
    commands: [{ command: "ping <passerelle>", purpose: "Tester la joignabilité IP du routeur local." }],
    evidence: "Écris ce que le test prouve, puis ce qu’il ne prouve pas.",
    challenge: "Comment un filtrage de ping peut-il produire un faux sentiment de panne ?",
    memoId: "network-windows",
  },
  {
    id: "jour-18-dns",
    phase: "Réseau",
    title: "DNS : quand l’IP marche mais pas le nom",
    duration: "20–25 min",
    objective: "Isoler la résolution de noms en comparant accès par IP et par nom.",
    concepts: ["dns", "ping", "ip"],
    briefing: [
      "Le DNS traduit un nom comme example.com en adresse IP.",
      "Une IP extérieure joignable suivie d’un nom introuvable oriente vers le DNS.",
    ],
    tasks: [
      "Lance nslookup example.com et repère le serveur interrogé.",
      "Note l’adresse obtenue.",
      "Distingue « délai d’attente » et « hôte introuvable ».",
      "Écris l’ordre des tests ciblant le DNS sans modifier la configuration.",
    ],
    commands: [
      { command: "nslookup example.com", purpose: "Interroger explicitement le DNS." },
      { command: "ping 1.1.1.1", purpose: "Tester une IP extérieure sans dépendre du DNS." },
    ],
    evidence: "Complète : « Si l’IP répond mais que le nom échoue, alors… »",
    challenge: "Trouve une autre cause qu’un serveur DNS en panne.",
    memoId: "network-windows",
  },
  {
    id: "jour-19-proche-lointain",
    phase: "Réseau",
    title: "Tester du proche au lointain",
    duration: "20–25 min",
    objective: "Construire une séquence où chaque résultat choisit l’étape suivante.",
    concepts: ["ping", "gateway", "dns", "ip"],
    briefing: [
      "Un diagnostic réseau progresse : configuration, local, passerelle, extérieur, DNS, service.",
      "Chaque test doit isoler un étage supplémentaire.",
    ],
    tasks: [
      "Ordonne : ipconfig, passerelle, IP extérieure, nom.",
      "Pour chaque test, écris la suite si le résultat réussit.",
      "Écris aussi la branche si le résultat échoue.",
      "Compare ton arbre à la fiche réseau.",
    ],
    evidence: "Tes notes doivent former un arbre de décision, pas une liste.",
    challenge: "Place la question « un seul appareil ou plusieurs ? » et justifie son emplacement.",
    memoId: "network-windows",
  },
  {
    id: "jour-20-commandes-reseau",
    phase: "Réseau",
    title: "Lire les commandes réseau",
    duration: "20–30 min",
    objective: "Interpréter une sortie avant de lancer une commande corrective.",
    concepts: ["ip", "dhcp", "dns", "gateway", "ping"],
    briefing: [
      "Une commande n’est utile que si tu sais quelle question elle pose.",
      "On commence par lire ; renouveler une adresse ou vider un cache modifie déjà l’état.",
    ],
    tasks: [
      "Associe chaque commande à une question précise.",
      "Dans ipconfig /all, repère adresse, DHCP, passerelle et DNS.",
      "Dans ping, distingue résolution du nom et réponses reçues.",
      "Dans nslookup, distingue serveur interrogé et adresse renvoyée.",
    ],
    commands: [
      { command: "ipconfig /all", purpose: "Quelle configuration le poste utilise-t-il ?" },
      { command: "ping <cible>", purpose: "La cible paraît-elle joignable par ICMP ?" },
      { command: "nslookup <nom>", purpose: "Quel résultat le DNS renvoie-t-il ?" },
    ],
    evidence: "Pour chaque commande, note une conclusion légitime et une abusive.",
    challenge: "Pourquoi « ping ne répond pas » et « le service est en panne » ne sont-ils pas équivalents ?",
    memoId: "network-windows",
  },
  {
    id: "jour-21-cas-wifi",
    phase: "Réseau",
    title: "Cas de synthèse : Wi‑Fi sans Internet",
    duration: "25–30 min",
    objective: "Séparer liaison Wi‑Fi, configuration IP, passerelle, extérieur et DNS.",
    concepts: ["ip", "dhcp", "gateway", "ping", "dns"],
    briefing: [
      "L’icône Wi‑Fi ne garantit ni une bonne configuration ni Internet.",
      "Le périmètre — un poste ou tous — reste le premier raccourci utile.",
    ],
    tasks: [
      "Joue la mission interactive « Le Wi‑Fi est connecté, Internet ne répond pas ».",
      "À chaque étape, nomme l’étage testé.",
      "Relis uniquement les fiches où tu as hésité.",
      "Rédige un arbre en six tests maximum.",
    ],
    evidence: "Inclue une branche 169.254.x.x et une branche DNS.",
    challenge: "Ajoute le cas où tous les appareils sont touchés.",
    memoId: "network-windows",
    relatedMissionId: "wifi-no-internet",
  },
  {
    id: "jour-22-droits-utiles",
    phase: "Support sûr",
    title: "Donner seulement les droits utiles",
    duration: "20–25 min",
    objective: "Appliquer le moindre privilège à des situations quotidiennes.",
    concepts: ["least-privilege", "phishing", "backup"],
    briefing: [
      "Un compte administrateur peut modifier profondément le système.",
      "Le moindre privilège accorde les droits nécessaires, au bon moment.",
    ],
    tasks: [
      "Classe : lire, installer, changer l’heure, créer un compte, modifier une sauvegarde.",
      "Décide si des droits élevés sont nécessaires.",
      "Compare les dégâts possibles d’un logiciel malveillant selon les droits du compte.",
      "Écris une règle d’usage quotidien et une règle d’intervention.",
    ],
    evidence: "Explique le moindre privilège en une phrase non technique.",
    challenge: "Pourquoi partager un compte administrateur affaiblit-il aussi le diagnostic ?",
    memoId: "before-intervention",
  },
  {
    id: "jour-23-autopsie-phishing",
    phase: "Support sûr",
    title: "Autopsier un message de phishing",
    duration: "20–25 min",
    objective: "Évaluer un message par faisceau d’indices sans cliquer.",
    concepts: ["phishing", "dns", "least-privilege"],
    briefing: [
      "Le phishing exploite urgence, autorité, peur ou récompense.",
      "Logo correct et langue impeccable ne prouvent rien.",
    ],
    tasks: [
      "Choisis un ancien message commercial ou une simulation.",
      "Compare nom affiché et adresse réelle de l’expéditeur.",
      "Survole un lien sans cliquer et vérifie le domaine.",
      "Liste les leviers psychologiques et une voie indépendante de vérification.",
    ],
    evidence: "Rédige : indices, risque, action recommandée et méthode de vérification.",
    challenge: "Pourquoi un message légitime peut-il tout de même paraître suspect ?",
    caution: "N’examine pas une pièce jointe ou un message dangereux réel.",
  },
  {
    id: "jour-24-sans-aggraver",
    phase: "Support sûr",
    title: "Répondre sans aggraver",
    duration: "20–25 min",
    objective: "Choisir une première action qui protège données et indices.",
    concepts: ["backup", "phishing", "least-privilege", "psu"],
    briefing: [
      "Urgent signifie réduire le dommage potentiel, pas agir au hasard.",
      "Odeur de brûlé, chiffrement suspect et compte compromis exigent des réponses différentes.",
    ],
    tasks: [
      "Classe : écran secondaire en panne, odeur électrique, phishing non ouvert, fichiers renommés.",
      "Choisis une action immédiate et une action interdite pour chaque cas.",
      "Justifie par impact, urgence et aggravation.",
      "Écris les informations à transmettre à la relève.",
    ],
    evidence: "Produis « incident / risque / première action / preuve à conserver ».",
    challenge: "Pourquoi redémarrer peut-il être utile dans un cas et destructeur d’indices dans un autre ?",
    memoId: "before-intervention",
  },
  {
    id: "jour-25-questionner",
    phase: "Support sûr",
    title: "Questionner avant de toucher",
    duration: "20–25 min",
    objective: "Transformer une plainte vague en description reproductible.",
    concepts: ["task-manager", "driver", "ping"],
    briefing: [
      "L’utilisateur décrit un effet, rarement le mécanisme.",
      "Depuis quand, qui est touché, ce qui marche et ce qui a changé sont des questions très rentables.",
    ],
    tasks: [
      "Pars de « ça ne marche plus » et écris dix questions.",
      "Réduis-les aux cinq qui changent le plus vite le diagnostic.",
      "Classe : périmètre, chronologie, reproduction, changement, impact.",
      "Reformule le problème en une phrase neutre.",
    ],
    evidence: "Conserve ce questionnaire de cinq lignes comme script de départ.",
    challenge: "Écris une question respectueuse qui vérifie une erreur de manipulation plausible.",
    memoId: "method",
  },
  {
    id: "jour-26-compte-rendu",
    phase: "Support sûr",
    title: "Écrire un compte rendu utile",
    duration: "20–25 min",
    objective: "Documenter symptôme, preuve, action et résultat sans formule vague.",
    concepts: ["backup", "driver", "ping", "task-manager"],
    briefing: [
      "« Problème réglé » ne permet ni de comprendre ni de reproduire.",
      "Un bon texte sépare observation, hypothèse et modification.",
    ],
    tasks: [
      "Choisis une petite panne déjà vécue.",
      "Écris une version volontairement mauvaise en une ligne.",
      "Réécris : contexte, symptôme, test, résultat, action, vérification.",
      "Supprime ce qui n’aide pas une reprise ultérieure.",
    ],
    evidence: "Le compte rendu final tient en huit lignes et distingue preuve et hypothèse.",
    challenge: "Ajoute une ligne précisant ce que tu n’as pas réussi à prouver.",
    memoId: "method",
  },
  {
    id: "jour-27-trier-incidents",
    phase: "Support sûr",
    title: "Trier trois incidents concurrents",
    duration: "20–25 min",
    objective: "Prioriser selon impact, urgence et aggravation possible.",
    concepts: ["phishing", "psu", "dns", "backup"],
    briefing: [
      "Le premier arrivé n’est pas toujours le premier à traiter.",
      "Une panne visible peut être moins prioritaire qu’un risque discret pour les données.",
    ],
    tasks: [
      "Classe : un site introuvable, un PC qui sent le chaud, cinq mots de passe saisis sur un faux site.",
      "Estime impact, urgence et aggravation.",
      "Choisis la première action et un message d’attente pour les autres.",
      "Réévalue si le site bloque toute l’entreprise.",
    ],
    evidence: "Écris l’ordre initial, l’ordre révisé et l’information qui l’a changé.",
    challenge: "Imagine un incident urgent mais peu impactant, puis l’inverse.",
    memoId: "before-intervention",
  },
  {
    id: "jour-28-diagnostic-mixte",
    phase: "Support sûr",
    title: "Ne pas suivre le premier suspect",
    duration: "25–30 min",
    objective: "Choisir entre piste Windows, réseau ou matérielle.",
    concepts: ["driver", "dns", "task-manager", "gateway", "ssd"],
    briefing: [
      "Plusieurs symptômes peuvent partager une cause ou simplement coïncider.",
      "Cherche un test discriminant avant de fusionner les problèmes.",
    ],
    tasks: [
      "Cas : navigateur lent, un seul site échoue, disque parfois à 100 %.",
      "Formule au moins trois hypothèses séparées.",
      "Choisis un test sans modification pour chacune.",
      "Ordonne les tests pour séparer site, DNS, réseau et stockage.",
    ],
    evidence: "Écris un arbre où chaque résultat mène à une hypothèse différente.",
    challenge: "Ajoute « le site échoue aussi sur le téléphone » et explique ce qui change.",
    memoId: "method",
  },
  {
    id: "jour-29-intervention-blanche",
    phase: "Synthèse",
    title: "Intervention blanche de bout en bout",
    duration: "30–35 min",
    objective: "Simuler une prise en charge complète sans modifier la machine.",
    concepts: ["task-manager", "driver", "ip", "dns", "backup", "least-privilege"],
    briefing: [
      "Tu joues le technicien sur un problème fictif et documentes chaque décision.",
      "Le but n’est pas de deviner vite, mais de construire un raisonnement vérifiable.",
    ],
    tasks: [
      "Cas : après une mise à jour, le PC démarre lentement et certains sites ne s’ouvrent plus.",
      "Écris questions initiales et précautions.",
      "Construis deux branches : lenteur Windows et accès réseau.",
      "Ajoute outils, résultats possibles et décisions.",
      "Termine par un compte rendu incluant ce qui reste incertain.",
    ],
    evidence: "Conserve questionnaire, arbre de diagnostic et compte rendu.",
    challenge: "Fixe la limite à laquelle tu demanderais de l’aide ou escaladerais.",
    memoId: "method",
  },
  {
    id: "jour-30-pret-rentree",
    phase: "Synthèse",
    title: "Préparer la rentrée sans se raconter d’histoires",
    duration: "30–40 min",
    objective: "Faire un bilan honnête et préparer un poste utilisable le premier jour.",
    concepts: ["bios", "driver", "task-manager", "ip", "dhcp", "dns", "backup", "phishing"],
    briefing: [
      "Être prêt ne signifie pas tout connaître, mais savoir observer, chercher, tester et documenter.",
      "Les erreurs du mois choisissent la prochaine révision ; elles ne fabriquent pas une note sur ta valeur.",
    ],
    tasks: [
      "Choisis les trois notions les moins solides dans ta carte des acquis.",
      "Explique chacune sans relire, puis corrige avec la fiche.",
      "Effectue une révision adaptative complète.",
      "Vérifie accès à la formation, navigateur, casque, sauvegarde, notes et temps réservé.",
      "Écris trois questions à poser pendant la première semaine.",
    ],
    evidence: "Fais trois colonnes : acquis fiables, notions à revoir, habitudes à maintenir.",
    challenge: "Explique à voix haute un des trois cas interactifs sans cliquer.",
    memoId: "method",
  },
];
